{ pkgs }: {
	deps = [
		pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-12_x
  pkgs.nodejs
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs
  pkgs.nodejs
  pkgs.nodejs
  pkgs.nodejs
  pkgs.nodejs
  pkgs.nodejs
  pkgs.nodejs
  pkgs.nodejs
  pkgs.nodejs
  pkgs.nodejs-16_x
  pkgs.nodejs
  pkgs.nodejs
  pkgs.nodejs
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.nodejs-16_x
  pkgs.npm start
  pkgs.clear
  pkgs.nodejs-18_x
    pkgs.nodePackages.typescript-language-server
    pkgs.yarn
    pkgs.replitPackages.jest
	];
}